version: '3.5'

services:
  # -------------------------
  # Base de Datos PostgreSQL
  # -------------------------
  postgres-server:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zabbix-net

  # -------------------------
  # Zabbix Server
  # -------------------------
  server:
    image: zabbix/zabbix-server-pgsql
    ports:
      - "10051:10051"
    depends_on:
      - postgres-server
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - zabbix-net

  # -------------------------
  # Zabbix Web Frontend
  # -------------------------
  web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql
    ports:
      - "8084:8080"
    depends_on:
      - server
      - postgres-server
    environment:
      - DB_SERVER_HOST=postgres-server
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - zabbix-net

  # -------------------------
  # Jenkins
  # -------------------------
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - zabbix-net

  # -------------------------
  # Portainer
  # -------------------------
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-data:/data
    restart: always

volumes:
  postgres-data:
  jenkins-data:

networks:
  zabbix-net:
